export default [
  {
    name: "Eğitim Danışmanlığı",
    desc: "Polonya’da eğitim alma amacıyla gelen danışanlarımıza üniversite, yaz okulu, dil okulu vb. Kayıt ve kabul işlemlerini profesyonel, güvenilir ve garantili bir şekilde yürütülmesi için aşağıda sunduğumuz hizmetlerden ücretsiz faydalanabilirler.",
    isMostPop: true,
    features: [
      "Online görüşme",
      "Dil okulları hakkında genel bilgiler",
      "Üniversiteler hakkında genel bilgiler ",
      "Polonya`da yaşam hakkında merak ettikleriniz",
      "Polonya'da hayatı kolaylaştıran uygulamaların listesinin paylaşılması",
    ],
  },
  {
    name: "Standart Paket",
    desc: "Polonya’da yeni eğitim hayatınızda Polonya Yaşam ailesinin profesyonel desteğini her alanda almayı talep eden danışanlarımız için aşağıda sunduğumuz hizmetlerden faydalanabilirler. Fiyat bilgisi için lütfen ekranın sağ altında bulunan simgeye tıklayın.",
    isMostPop: false,
    features: [
      "Olympos Portal Servisi",
      "Ücretsiz ön görüşme",
      "Dil Okulu - Dil Hazırlık Kursu Araştırması",
      "Dil Okulu İçin Araştırma",
      "Kişiye özel üniversite ve bölüm araştırması",
      "Üniversite Bölüm Kayıt ve Kabul İşlemleri (Lisans ve Yüksek Lisans Eğitimi)",
      "Vize İçin Gerekli Evrakların Hazırlanması ve kontrolü",
      "Vize İçin Sigorta İşlemleri",
      "Vize Reddi Durumunda İtiraz İşlemleri",
      "Ulaşım Organizasyonu",
      "Havaalanı Karşılaması ve konaklama yerine ulaşım",
      "Şehir Turu ve Oryantasyon",
      "PESEL Numarası Alma İşlemleri",
      "Ulaşım Kartı İşlemleri",
      "Telefon Hattı İşlemleri",
      "Evrak Tercüme Desteği",
    ],
  },
  {
    name: "Kapsamlı Paket",
    desc: "Polonya’da yeni eğitim hayatınızda Polonya Yaşam ailesinin profesyonel desteğini her alanda almayı talep eden danışanlarımız için aşağıda sunduğumuz hizmetlerden faydalanabilirler. Fiyat bilgisi için lütfen ekranın sağ altında bulunan simgeye tıklayın.",
    isMostPop: true,
    features: [
      "Olympos Portal Servisi",
      "Ücretsiz ön görüşme",
      "Dil Okulu - Dil Hazırlık Kursu Araştırması",
      "Dil Okulu İçin Araştırma",
      "Kişiye özel Üniversite ve Bölüm Araştırması",
      "Üniversite Bölüm Kayıt ve Kabul İşlemleri (Lisans ve Yüksek Lisans Eğitimi)",
      "Vize İçin Destekleyici Evrakların Hazırlanması ve kontrolü",
      "Vize Reddi Durumunda İtiraz İşlemleri",
      "Vize İçin Sigorta İşlemleri",
      "Şehir Turu ve Oryantasyon",
      "Konaklama Yerinin Ayarlanması",
      "Uçak, Otobüs vb. Ulaşım Organizasyonu",
      "Havaalanı Karşılaması",
      "Konaklama Yerine Ulaşım",
      "Şehir Turu ve Oryantasyon",
      "Telefon Hattı İşlemleri",
      "Banka Hesabı İşlemleri",
      "PESEL Numarası Alma İşlemleri",
      "Evrak Tercüme Desteği",
      "Oturum İzni İşlemleri",
    ],
  },
];
