const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Bölüm", uid: "program", sortable: true },
  { name: "Üniversite Adı", uid: "uni", sortable: true },
  { name: "Lisans Türü", uid: "type", sortable: true },
  { name: "Fiyat/Sömestr", uid: "price" },
];

const programs = [
  {
    id: 1,
    program: "Mimarlık",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "5410 Euro",
  },
  {
    id: 2,
    program: "Çevre Mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 3,
    program: "Uzay Mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2100 Euro",
  },
  {
    id: 4,
    program: "Yönetim ",
    type: "lisans",
    uni: "Kozminski Üniversitesi",
    price: "3960 Euro",
  },
  {
    id: 5,
    program: "Finansal yönetim",
    type: "lisans",
    uni: "Kozminski Üniversitesi",
    price: "3960 Euro",
  },
  {
    id: 6,
    program: "Yönetim ve yapay zeka",
    type: "lisans",
    uni: "Kozminski Üniversitesi",
    price: "3960 Euro",
  },
  {
    id: 7,
    program: "Medicine",
    type: "lisans",
    uni: "Collegium Humanum Üniversitesi",
    price: "5800 Euro",
  },
  {
    id: 8,
    program: "Bilgisayar Bilimleri (IT)",
    type: "lisans",
    uni: "Polonya-Japonya Bilgi Teknolojileri Enstitüsü",
    price: "2800 Euro",
  },
  {
    id: 9,
    program: "Bilgi Yönetimi",
    type: "lisans",
    uni: "Polonya-Japonya Bilgi Teknolojileri Enstitüsü",
    price: "2400 Euro",
  },
  {
    id: 10,
    program: "Bilgisayar Bilimleri (IT)",
    type: "lisans",
    uni: "SWPS Üniversitesi",
    price: "2250 Euro",
  },
  {
    id: 11,
    program: "Finans, Uluslararası Yatırım ve Muhasebe",
    type: "lisans",
    uni: "Varşova Üniversitesi",
    price: "1600 Euro",
  },
  {
    id: 12,
    program: "Management",
    type: "lisans",
    uni: "SGH Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 13,
    program: "International Economics",
    type: "lisans",
    uni: "SGH Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 14,
    program: "Quantitative Methods in Economics and Information Systems",
    type: "lisans",
    uni: "SGH Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 15,
    program: "Global Business, Finance and Governance",
    type: "lisans",
    uni: "SGH Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 16,
    program: "Biyoteknoloji",
    program: " Biyoteknoloji",
    type: "lisans",
    uni: "Varşova Yaşam Bilimleri Üniversitesi",
    price: "168700 Euro",
  },
  {
    id: 17,
    program: "Uluslararası İlişkiler",
    type: "lisans",
    uni: "Varşova Yaşam Bilimleri Üniversitesi",
    price: "152420 Euro",
  },
  {
    id: 18,
    program: "Çevre Mühendisliği",
    type: "lisans",
    uni: "Varşova Yaşam Bilimleri Üniversitesi",
    price: "152424 Euro",
  },
  {
    id: 19,
    program: "Tıp",
    type: "lisans",
    uni: "Varşova Medikal Üniversitesi",
    price: "5550 Euro",
  },
  {
    id: 20,
    program: "Diş Hekilik",
    program: "Diş Hekimliği",
    type: "lisans",
    uni: "Varşova Medikal Üniversitesi",
    price: "7500 Euro",
  },
  {
    id: 21,
    program: "Eczacılık",
    type: "lisans",
    uni: "Varşova Medikal Üniversitesi",
    price: "2850 Euro",
  },
  {
    id: 22,
    program: "Ressamlık",
    type: "lisans",
    uni: "Varşova Güzel Sanatlar Akademisi",
    price: "581000 Euro",
  },
  {
    id: 23,
    program: "Heykeltraş",
    type: "lisans",
    uni: "Varşova Güzel Sanatlar Akademisi",
    price: "581000 Euro",
  },
  {
    id: 24,
    program: "Grafik Tasarımı",
    type: "lisans",
    uni: "Varşova Güzel Sanatlar Akademisi",
    price: "1350 Euro",
  },
  {
    id: 25,
    program: "Law in international Relations and business",
    type: "lisans",
    uni: "Lazarski Üniversitesi",
    price: "2280 Euro",
  },
  {
    id: 26,
    program: "İşletme",
    type: "lisans",
    uni: "Lazarski Üniversitesi",
    price: "1350 Euro",
  },
  {
    id: 27,
    program: "İngilizce Hazırlık",
    type: "lisans",
    uni: "SWPS Üniversitesi",
    price: "1600 Euro",
  },
  {
    id: 28,
    program: "İngilizce Hazırlık",
    type: "lisans",
    uni: "Lazarski Üniversitesi",
    price: "1775 Euro",
  },
  {
    id: 30,
    program: "İngilizce hazırlık",
    type: "lisans",
    uni: "Varşova Yaşam Bilimleri Üniversitesi swps",
    price: "1600 Euro",
  },
  {
    id: 31,
    program: "İngilizce hazırlık",
    type: "lisans",
    uni: "Varşova Yaşam Bilimleri Üniversitesi",
    price: "1625 Euro",
  },
  {
    id: 32,
    program: "İngilizce Hazırlık",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "1950 Euro",
  },
  {
    id: 33,
    program: "Psikoloji",
    type: "yüksek lisans",
    uni: "SWPS Üniversitesi",
    price: "3875 Euro",
  },

  {
    id: 34,
    program: "Yönetim ve Liderlik",
    type: "yüksek lisans",
    uni: "SWPS Üniversitesi",
    price: "2925 Euro",
    program: "Otomotiv ve inşaat makineleri mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "3250 Euro",
  },
  {
    id: 35,
    program: "Genetik ve Moleküler Biyoloji",
    type: "yüksek lisans",
    program: "Elektrik Mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2200 Euro",
    price: "3250 Euro",
  },
  {
    id: 36,
    program: "Bilgisayar Bilimleri (IT)",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "5610 Euro",
  },
  {
    id: 37,
    program: "Mekatronik",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2990 Euro",
  },
  {
    id: 38,
    program: "Havacılık ve Uzay Mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2100 Euro",
  },
  {
    id: 39,
    program: "Bilgisayar Bilimi ve Bilgi Sistemleri",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "5619 Euro",
  },
  {
    id: 40,
    program: "İnşaat Mühendisliği",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "4500 Euro",
  },
  {
    id: 41,
    program: "Bilgisayar sistemleri ve Ağları",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "5530 Euro",
  },
  {
    id: 42,
    program: "Telekominasyon",
    type: "lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "5520 Euro",
  },
  {
    id: 43,
    program: "Garfik Tasarım",
    type: "lisans",
    uni: "Polonya-Japonya Bilgi Teknolojileri Enstitüsü",
    price: "2800 Euro",
  },
  {
    id: 44,
    program: "Yönetim ve liderlik",
    type: "lisans",
    uni: "SWPS Üniversitesi",
    price: "2875 Euro",
  },
  {
    id: 45,
    program: "Mimarlık",
    type: "doktora",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "1400 Euro",
  },
  {
    id: 46,
    program: "Şehir ve Bölge Planlaması",
    type: "doktora",
    program: "Şehir ve bölge planlama",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "1650 Euro",
  },
  {
    id: 48,
    program: "Kimya ve Proses Mühendisliği",
    type: "doktora",
    program: "Çevre Mühendisliği",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 49,
    program: "Kimya ve Proses mühendisliği",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "2400 Euro",
  },
  {
    id: 50,
    program: "İnşaat Mühendisliği",
    type: "doktora",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "4900 Euro",
  },
  {
    id: 51,
    program: "Elektrik Mühendisliği",
    type: "doktora",
    program: "Elektrik mühendisliği",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "3900 Euro",
  },
  {
    id: 52,
    program: "Bilgisayar Bilimleri",
    type: "doktora",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "1650 Euro",
  },
  {
    id: 53,
    program: "Telekomünikasyon",
    type: "doktora",
    program: "Telekominasyon",
    type: "yüksek lisans",
    uni: "Varşova Teknoloji Üniversitesi",
    price: "6950 Euro",
  },
  {
    id: 54,
    program: "Psikoloji",
    type: "yüksek lisans",
    uni: "SWPS Üniversitesi",
    price: "3875 Euro",
  },
  {
    id: 55,
    program: "Yönetim ve Liderlik",
    type: "yüksek lisans",
    uni: "SWPS Üniversitesi",
    price: "2925 Euro",
  },
];

export { columns, programs };
